
//output_type
#define RECTLINEAR			0x00
#define WIDE_PANORAMA		0x01
#define	EQUIRECTANGULAR		0x02
#define	CIRCULAR_FISHEYE	0x03
#define	FULL_FRAME_FISHEYE	0x04
#define STEREO				0x05

//input_type
#define RECTLINEAR			0x00
#define WIDE_PANORAMA		0x01
#define	CIRCULAR_FISHEYE	0x02
#define	FULL_FRAME_FISHEYE	0x03

// for warp
//#define	RECTLINEAR_TO_PANORAMA					0x202
//#define FULL_FRAME_FISHEYE_TO_CYLINDRICAL		0x201
//#define FULL_FRAME_FISHEYE_TO_STEREOGRAPHIC		0x106
//#define CIRCULAR_FISH_TO_STEREOGRAPHIC			0x105
#define LENS_TYPE_THE_NUMBER					0x04
//#define FULL_FRAME_FISHEYE_TO_EQUIRECT			0x03
//#define CIRCULAR_FISH_TO_EQUIRECT				0x02
//#define CYLINDRICAL_PANORAMA_TO_EQUIRECT		0x01
//#define RECTLINEAR_TO_EQUIRECT					0x00

#define FOR_360_INPUT							0x00
#define NOT_FOR_360_INPUT						0x01

#define INPUT_STATE_NO_DRAW				0x01
#define INPUT_STATE_DRAW				0x02

#define SIMPLE_BLEND			0x01
#define NO_GAIN_COMPENSATION	0x00
#define GAIN_AVERAGE_COMPENSATION_FULL		0x01
#define GAIN_RGB_COMPENSATION_FULL	0x02
//#define GAIN_CURVE_MANUAL_RGB_COMPENSATION 0x03
#define GAIN_CURVE_AUTO_RGB_COMPENSATION 0x03
#define GAIN_CURVE_AUTO_AVERAGE_COMPENSATION 0x04


#define GAIN_CURVE_MANUAL_AVERAGE_COMPENSATION 0x06
#define GAIN_YUV_COMPENSATION_FULL	0x07
#define GAIN_YUV_COMPENSATION_HALF	0x08

#define GAIN_MANUAL					0x00
#define GAIN_AUTO					0x01

#define NO_AVAILABLE_SOUND			0x01
#define AVAILABLE_SOUND				0x02

//#define FULL_GAIN_COMPENSATION	0x00
//#define HALF_GAIN_COMPENSATION	0x01

#define STITCHING_2BY1			0x00
#define STITCHING_16BY9			0x01

#define MAX_NUM_OVERLAY				3

// overlay state
#define READY_TO_ADD_OVERLAY		0x01
#define ADDED_OVERLAY				0x02
#define READY_TO_DESTROY_OVERLAY	0x03
#define SELECTED_OVERLAY			0x04
#define UNSELECTED_OVERLAY			0x05
#define READY_TO_MODIFY_OVERLAY		0x06
#define FADE_IN_OVERLAY				0x07
#define FADE_OUT_OVERLAY			0x08
#define WAIT_FOR_SHOWING_OVERLAY	0x09

// stitching mode
#define EDIT_OVERLAY			0x10
#define CHANGE_OVERLAY_STATE	0x09
#define UNDO_REDO_TRY			0x03
#define UNDO_REDO_DONE			0x13
#define UNDO_REDO_MASK_DONE		0x14
#define ROTATE_MODE				0x02
#define ANIMATION_MODE			0x07
#define STITCHING_TEMPLATE_REFRESH		0x04
#define STITCHING_INIT		0x01
#define STITCHING_LOAD		0x05

#define STEREO_STITCHING_LR		0x14
#define STEREO_STITCHING_TB		0x15
#define STITCHED_INPUT			0x16
#define WIDE_STITCHING			0x17

//ComposeHelper Mode
#define COMPOSEHELPER_ROI		0x01
#define COMPOSEHELPER_REGION	0x02
#define COMPOSEHELPER_EDIT		0x03

// Edit ScaleFactor
#define BRIGHTNESS_FACTOR		0.02
#define CONTRAST_FACTOR			0.1

// Stitching Editing Mode
#define STITCHING_MODE			0x01
#define STITCHING_EDIT_MODE		0x05