// XTPDockingPaneResource.h
//
// (c)1998-2016 Codejock Software, All Rights Reserved.
//
// THIS SOURCE FILE IS THE PROPERTY OF CODEJOCK SOFTWARE AND IS NOT TO BE
// RE-DISTRIBUTED BY ANY MEANS WHATSOEVER WITHOUT THE EXPRESSED WRITTEN
// CONSENT OF CODEJOCK SOFTWARE.
//
// THIS SOURCE CODE CAN ONLY BE USED UNDER THE TERMS AND CONDITIONS OUTLINED
// IN THE XTREME TOOLKIT PRO LICENSE AGREEMENT. CODEJOCK SOFTWARE GRANTS TO
// YOU (ONE SOFTWARE DEVELOPER) THE LIMITED RIGHT TO USE THIS SOFTWARE ON A
// SINGLE COMPUTER.
//
// CONTACT INFORMATION:
// support@codejock.com
// http://www.codejock.com
//
/////////////////////////////////////////////////////////////////////////////

#define XTP_DOCKINGPANE_RESOURCE_FIRST          9475
#define XTP_DOCKINGPANE_RESOURCE_LAST           9499

#define XTP_IDB_DOCKINGPANE_VISIOGRIPPER        9475
#define XTP_IDB_DOCKINGPANE_STICKER_CLIENT      9476
#define XTP_IDB_DOCKINGPANE_STICKERS_BLUE       9477
#define XTP_IDB_DOCKINGPANE_STICKERS_OLIVE      9478
#define XTP_IDB_DOCKINGPANE_STICKERS_SILVER     9479
#define XTP_IDB_DOCKINGPANE_STICKERS_2005       9480
#define XTP_IDB_DOCKINGPANE_STICKERS_2008       9481
#define XTP_IDB_DOCKINGPANE_STICKERS_2010       9482
#define XTP_IDB_DOCKINGPANE_STICKERS_2012_LIGHT 9483
#define XTP_IDB_DOCKINGPANE_STICKERS_2012_DARK  9484
#define XTP_IDB_DOCKINGPANE_STICKERS_2015_LIGHT 9485
#define XTP_IDB_DOCKINGPANE_STICKERS_2015_BLUE  9486
#define XTP_IDB_DOCKINGPANE_STICKERS_2015_DARK  9487

#define XTP_IDS_DOCKINGPANE_AUTOHIDE            9488
#define XTP_IDS_DOCKINGPANE_CLOSE               9489
#define XTP_IDS_DOCKINGPANE_MAXIMIZE            9490
#define XTP_IDS_DOCKINGPANE_RESTORE             9491
#define XTP_IDS_DOCKINGPANE_MENU                9492
#define XTP_IDS_DOCKINGPANE_SELECTWINDOW_ACTIVETOOLS  9493
#define XTP_IDS_DOCKINGPANE_SELECTWINDOW_ACTIVEFILES  9494
